### ISSUE TITLE
Sometimes 404 happens 

### ISSUE THREAD

**Issue by Otanikotani** [Otanikotani/view-github-actions-idea-plugin#14]
Stacktrace:
```
java.io.UncheckedIOException: org.jetbrains.plugins.github.exceptions.GithubStatusCodeException: 404 Not Found - Not Found
	at org.github.otanikotani.ui.toolwindow.GettingCheckSuites.run(GettingCheckSuites.java:62)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:888)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:163)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:585)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:531)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:150)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.lambda$run$0(CoreProgressManager.java:402)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:221)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:402)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:238)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.jetbrains.plugins.github.exceptions.GithubStatusCodeException: 404 Not Found - Not Found
	at org.jetbrains.plugins.github.api.GithubApiRequestExecutor$Base.checkResponseCode(GithubApiRequestExecutor.kt:189)
	at org.jetbrains.plugins.github.api.GithubApiRequestExecutor$Base.access$checkResponseCode(GithubApiRequestExecutor.kt:110)
	at org.jetbrains.plugins.github.api.GithubApiRequestExecutor$Base$execute$1.process(GithubApiRequestExecutor.kt:124)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:518)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:500)
	at com.intellij.util.io.HttpRequests.access$100(HttpRequests.java:56)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:350)
	at org.jetbrains.plugins.github.api.GithubApiRequestExecutor$Base.execute(GithubApiRequestExecutor.kt:115)
	at org.jetbrains.plugins.github.api.GithubApiRequestExecutor$WithTokenAuth.execute(GithubApiRequestExecutor.kt:75)
	at org.github.otanikotani.ui.toolwindow.GettingCheckSuites.run(GettingCheckSuites.java:60)
	... 15 more
```

This is quite annoying as IDEA would report it as a failure. We need to wrap this exception

**Comment by Otanikotani** [comment]
Fixed
